using System;
using System.Collections.Generic;
using System.Drawing;
using Grasshopper;
using Grasshopper.Kernel;
using Grasshopper.Kernel.Types;
using Rhino.Geometry;
using Woodpecker.Animation.Geometry.Display;
using Woodpecker.Animation.Util.IO;

namespace Woodpecker.Animation.GHComponents
{
    public class GH_DisplayClippingGeometryWire : GH_DisplayGeometryAbstract
    {
        public GH_DisplayClippingGeometryWire() :
            base(
                "Display Clipping Geometry Wire",
                "DispCWire",
                "Displays clipped geometry wireframes and optionally draws the section curves generated by each clipping plane.")
        {
            _renderClippingPipeline =
                new RenderClippingPipeline(
                    new List<DisplayClippingContent>(),
                    this,
                    GeometryRenderMode.Wire);
            _conduit = new DisplayGeometryConduit();
            _conduit.Register(_renderClippingPipeline);
            _conduit.Enabled = true;
        }
        public override Guid ComponentGuid => new Guid("35f55dac-8861-48e7-b662-e1d929f6c883");

        protected override void RegisterInputParams(GH_InputParamManager pManager)
        {
            pManager.AddGeometryParameter("Geometry", "G", "Geometry to Clip", GH_ParamAccess.tree);
            pManager.AddPlaneParameter("Clipping Planes", "CLs", "the planes to clip the geometry", GH_ParamAccess.list);
            pManager.AddColourParameter("Colour", "Col", "Color of the geometry.", GH_ParamAccess.item);
            pManager.AddBooleanParameter("Show Clipping Section Wire", "S", "Draw the intersection curves on the clipping planes.", GH_ParamAccess.item, true);
            pManager.AddIntegerParameter("Width", "W", "Line width for the clipped geometry and section curves.", GH_ParamAccess.item, 1);
            pManager.AddNumberParameter("Pointer_t", "t", "Time parameter for fade effect (0 to 1).", GH_ParamAccess.tree, 1.0);
        }
        protected override void RegisterOutputParams(GH_OutputParamManager pManager)
        {
            // No outputs needed for a display component.
        }
        protected override void SolveInstance(IGH_DataAccess DA)
        {
            if (!DA.GetDataTree<IGH_GeometricGoo>(
                    "Geometry",
                    out var geometryTree) ||
                geometryTree == null)
            {
                ClearDisplayContents();
                return;
            }

            var clippingPlanes = new List<Plane>();
            if (!DA.GetDataList(
                    "Clipping Planes",
                    clippingPlanes) ||
                clippingPlanes.Count == 0)
            {
                ClearDisplayContents();
                return;
            }

            var colour = Color.Black;
            var showSectionWire = true;
            var width = 1;
            DA.GetData("Colour", ref colour);
            DA.GetData(
                "Show Clipping Section Wire",
                ref showSectionWire);
            DA.GetData("Width", ref width);
            DA.GetDataTree<GH_Number>(
                "Pointer_t",
                out var pointerTree);

            var geometryData =
                new DataTree<GeometryBase>();
            var pointerData =
                new DataTree<double>();
            DataUtil.GH_Structure2GH_DataTree(
                geometryTree,
                ref geometryData);
            DataUtil.GH_Structure2GH_DataTree(
                pointerTree,
                ref pointerData);
            pointerData = DataUtil.AlignDataTree(
                geometryData,
                pointerData);

            var geometries = geometryData.AllData();
            var pointerValues = pointerData.AllData();
            var contents =
                new List<DisplayClippingContent>();

            for (var i = 0; i < geometries.Count; i++)
            {
                var content =
                    new DisplayClippingContent(
                        geometries[i],
                        colour,
                        clippingPlanes,
                        false,
                        showSectionWire);
                content.Width = width;
                content.SetT(pointerValues[i]);
                contents.Add(content);
            }

            _renderClippingPipeline.Stage =
                SelectedRenderStage;
            _renderClippingPipeline.SetContents(
                contents);
            SynchronizePreviewState();
        }
        protected override IRenderPipeline renderPipeline => _renderClippingPipeline;
        private readonly RenderClippingPipeline _renderClippingPipeline;
        public override BoundingBox ClippingBox =>
            _renderClippingPipeline?.ClippingBox ??
            BoundingBox.Empty;
    }
}
